// Copyright (c) 2025 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bborbe/cqrs/cdb/k8s/apis/cdb.benjamin-borbe.de/v1"
	cdbbenjaminborbedev1 "github.com/bborbe/cqrs/cdb/k8s/client/applyconfiguration/cdb.benjamin-borbe.de/v1"
	typedcdbbenjaminborbedev1 "github.com/bborbe/cqrs/cdb/k8s/client/clientset/versioned/typed/cdb.benjamin-borbe.de/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSchemas implements SchemaInterface
type fakeSchemas struct {
	*gentype.FakeClientWithListAndApply[*v1.Schema, *v1.SchemaList, *cdbbenjaminborbedev1.SchemaApplyConfiguration]
	Fake *FakeCdbV1
}

func newFakeSchemas(fake *FakeCdbV1, namespace string) typedcdbbenjaminborbedev1.SchemaInterface {
	return &fakeSchemas{
		gentype.NewFakeClientWithListAndApply[*v1.Schema, *v1.SchemaList, *cdbbenjaminborbedev1.SchemaApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("schemas"),
			v1.SchemeGroupVersion.WithKind("Schema"),
			func() *v1.Schema { return &v1.Schema{} },
			func() *v1.SchemaList { return &v1.SchemaList{} },
			func(dst, src *v1.SchemaList) { dst.ListMeta = src.ListMeta },
			func(list *v1.SchemaList) []*v1.Schema { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.SchemaList, items []*v1.Schema) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
