// Copyright (c) 2025 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bborbe/cqrs/cdb/k8s/client/clientset/versioned/typed/cdb.benjamin-borbe.de/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCdbV1 struct {
	*testing.Fake
}

func (c *FakeCdbV1) Schemas(namespace string) v1.SchemaInterface {
	return newFakeSchemas(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCdbV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
