// Copyright (c) 2025 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/bborbe/cqrs/cdb/k8s/apis/cdb.benjamin-borbe.de/v1"
	cdbbenjaminborbedev1 "github.com/bborbe/cqrs/cdb/k8s/client/applyconfiguration/cdb.benjamin-borbe.de/v1"
	internal "github.com/bborbe/cqrs/cdb/k8s/client/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=cdb, Version=v1
	case v1.SchemeGroupVersion.WithKind("Schema"):
		return &cdbbenjaminborbedev1.SchemaApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SchemaSpec"):
		return &cdbbenjaminborbedev1.SchemaSpecApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
